package com.order.manager.exception.code;

public enum ErrorCode {

    USERID_EXIST_ERROR,
    PHONE_EXIST_ERROR,
    SAME_PASSWORD_ERROR,
    INVALID_FORMAT_ERROR,

    ACCOUNT_NOT_FOUND_ERROR,
    EMPTY_VALUE_ERROR,
    NULL_VALUE_ERROR,
    EMPTY_ORDER_LIST_ERROR,
    EMPTY_DELIVERY_ERROR,
    EMPTY_DELIVERY_LIST_ERROR,

    INVALID_ORDER_TYPE_ERROR,
    NOT_STATE_IN_DELIVERY_ERROR,
    NOT_STATE_IN_READY_ERROR,
    NOT_STATE_IN_WAITING_ERROR,
    NOT_STATE_IN_DISPATCH_ERROR,
    NOT_STATE_IN_PICKUP_ERROR,
    NOT_FOUND_STATE_CODE_ERROR,
    CHANGE_ORDER_STATE_ERROR,
    DRIVER_MISMATCH_ERROR,
    COMPANY_MISMATCH_ERROR
}
