package com.order.manager.exception.code;

public enum ErrorCode {
    ENTITY_NOT_FOUND_ERROR,
    SAME_PASSWORD_ERROR,
    EMPTY_ORDER_LIST_ERROR,
    EMPTY_RESULT_DATE_ACCESS_ERROR,
    INVALID_ORDER_TYPE_ERROR,
    NOT_DELIVERY_ERROR,
    NOT_READY_ERROR,
    NOT_WAITING_ERROR,
    EMPTY_DELIVERY_ERROR,
    DRIVER_MISMATCH_ERROR,
    NOT_STATE_IN_DISPATCH_ERROR,
    NOT_STATE_IN_PICKUP_ERROR,
    NOT_FOUND_STATE_CODE_ERROR,
    EMPTY_DELIVERY_LIST_ERROR,
    PHONE_EXIST_ERROR,
    USERID_EXIST_ERROR
}
